# --- !Ups
CREATE TABLE "CHANNELS" (
  "ID" BIGSERIAL PRIMARY KEY NOT NULL,
  "NAME" VARCHAR(255) NOT NULL,
  "DESC" VARCHAR(255) NULL
);
CREATE TABLE "LOGS" (
  "ID" BIGSERIAL PRIMARY KEY NOT NULL,
  "IDCHANNEL" INTEGER,
  "USERNAME" VARCHAR(255) NOT NULL,
  "MESSAGE" TEXT,
  "POSTED" TIMESTAMP
);
ALTER TABLE "LOGS" ADD CONSTRAINT "FK_ID_CHANNEL" FOREIGN KEY("IDCHANNEL") REFERENCES "CHANNELS"("ID") ON UPDATE CASCADE ON DELETE CASCADE;

# --- !Downs
ALTER TABLE "CHANNELS" DROP CONSTRAINT "FK_ID_CHANNEL";

DROP TABLE "CHANNELS";
DROP TABLE "LOGS";
